/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rustfisher_appndkground_jni_ContextUtils */

#ifndef _Included_com_rustfisher_appndkground_jni_ContextUtils
#define _Included_com_rustfisher_appndkground_jni_ContextUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rustfisher_appndkground_jni_ContextUtils
 * Method:    nGetPkgName
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rustfisher_appndkground_jni_ContextUtils_nGetPkgName
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_rustfisher_appndkground_jni_ContextUtils
 * Method:    nPkgNameInList
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rustfisher_appndkground_jni_ContextUtils_nPkgNameInList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_rustfisher_appndkground_jni_ContextUtils
 * Method:    nGetApkSignedInfo
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rustfisher_appndkground_jni_ContextUtils_nGetApkSignedInfo
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
